export const CITY = [
  "Lagos",
  "Abuja",
  "Ibadan",
  "Port Harcourt",
  "Lekki Phase 1",
  "Victoria Island",
  "Yaba",
  "Marina",
  "Wuse II",
  "Maitama",
  "Ikoyi - Dolphin Estate",
  "Supermarket Online",
  "Pharmacy Online",
  "Shopping Online",
];

export const CUISINES = [
  "Burgers in Lagos",
  "Pizza in Lagos",
  "Nigerian Food in Lagos",
  "African Food in Lagos",
  "Chinese Food in Lagos",
  "Indian Food in Lagos",
  "American Food in Lagos",
  "Seafood in Lagos",
  "Breakfast Menu in Lagos",
  "Cakes in Lagos",
  "Sandwiches in Lagos",
  "Salads in Lagos",
  "Pasta in Lagos",
  "African Food in Abuja",
  "Sandwiches in Abuja",
  "Salads in Abuja",
  "Nigerian Food in Abuja",
];

export const POPULAR_VENDORS = [
  "Shiro",
  "Bambo Lounge",
  "Cilantro Delivery",
  "Bungalow Restaurant",
  "Chicken Capitol",
  "Chicken Republic",
  "Casper & Gambini's",
  "Johnny Rockets",
  "Drumstix",
  "Seven Eagles Spur",
  "Hard Rock Cafe",
  "Eric Kayser",
  "Kohinoor Lounge",
  "Krispy Kreme Doughnuts & Coffee",
  "Crepaway",
  "Debonairs Pizza",
  "KFC Delivery",
  "The Place",
  "Bukka Hut",
  "Pizza Hut",
  "Cold Stone Creamery",
  "Rhapsody's",
  "Spice Route",
  "355 Restaurant & Lounge Landmark",
  "China wok",
  "Terra Kulture",
  "All restaurants near me",
];

export const JUMIA_FOOD = [
  "About",
  "Press",
  "Contact",
  "Terms and Conditions",
  "Privacy Policy",
  "Jumia Food Prime - Unlimited Free Delivery",
  "Become a rider!",
  "Sell on Jumia Food",
  "vendors",
];
